[dev]
  command = "yarn dev"
  publish = "public"
  functions = "functions"
  port = 8888 # Port that the proxy server will listen on

[build]
  command = "yarn netlify-build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "15.14.0"
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.10"

[[plugins]]
  package = "@netlify/plugin-gatsby"
